apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationDefinition
metadata:
  name: ln-cm1
spec:
  description: Deploys a cm1
  method: helm
  versions:
    - template:
        source:
          git:
            path: examplechart
            ref:
              branch: main
            remote: https://github.com/hdurand0710/test-application1.git
        templateCredentials:
          helmCredentials:
              # registryConfigFile:
              #   key: .dockerconfigjson
              #   name: ln-helm-oci-private
              password:
                key: pass
                name: ln-helm-for-app      
              username:
                key: user
                name: ln-helm-for-app 
      version: 1.0.0
    - template:
          source:
             helm:
               chartName: examplechart
               chartVersion: 0.1.0
               url: https://demo.goharbor.io/chartrepo/helene
      version: 1.0.1
    - template:
          source:
             helm:
               chartName: examplechart
               chartVersion: 0.1.0
               url: oci://demo.goharbor.io/heleneprivate
      version: 1.0.2